# Generated by Django 4.2.8 on 2023-12-13 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cities_light", "0011_alter_city_country_alter_city_region_and_more"),
        ("providers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Good",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(editable=False)),
                ("modified_at", models.DateTimeField(editable=False)),
                (
                    "name",
                    models.CharField(max_length=500, unique=True, verbose_name="name"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("G", "Goods"), ("S", "Services"), ("W", "Works")],
                        max_length=1,
                        verbose_name="category",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gcreator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_modify_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gmodifier",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "goods",
                "db_table_comment": "Goods required by Unicef",
                "ordering": ["name"],
                "get_latest_by": ["created_at", "modified_at"],
                "default_related_name": "goods",
            },
        ),
        migrations.CreateModel(
            name="GoodsProvided",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(editable=False)),
                (
                    "good",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="providers.good"
                    ),
                ),
            ],
            options={
                "db_table": "goods_provided",
                "db_table_comment": "Goods actually provided by the providers retained by Unicef per city",
                "get_latest_by": ["created_at"],
                "default_related_name": "goods_provided",
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(editable=False)),
                ("modified_at", models.DateTimeField(editable=False)),
                (
                    "name",
                    models.CharField(max_length=500, unique=True, verbose_name="name"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="screator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_modify_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="smodifier",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "services",
                "db_table_comment": "Services required by Unicef",
                "ordering": ["name"],
                "get_latest_by": ["created_at", "modified_at"],
                "default_related_name": "services",
            },
        ),
        migrations.CreateModel(
            name="ServicesProvided",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(editable=False)),
            ],
            options={
                "db_table": "services_provided",
                "db_table_comment": "Services actually provided by the providers retained by Unicef per city",
                "get_latest_by": ["created_at"],
                "default_related_name": "services_provided",
            },
        ),
        migrations.CreateModel(
            name="Work",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(editable=False)),
                ("modified_at", models.DateTimeField(editable=False)),
                (
                    "name",
                    models.CharField(max_length=500, unique=True, verbose_name="name"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wcreator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_modify_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wmodifier",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "works",
                "db_table_comment": "Works required by Unicef",
                "ordering": ["name"],
                "get_latest_by": ["created_at", "modified_at"],
                "default_related_name": "works",
            },
        ),
        migrations.CreateModel(
            name="WorkExecuted",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(editable=False)),
                (
                    "good",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="providers.work"
                    ),
                ),
            ],
            options={
                "db_table": "works_executed",
                "db_table_comment": "Works actually provided by the providers retained by Unicef per city",
                "get_latest_by": ["created_at"],
                "default_related_name": "works_executed",
            },
        ),
        migrations.RemoveField(model_name="offersprovided", name="city",),
        migrations.RemoveField(model_name="offersprovided", name="offer",),
        migrations.RemoveField(model_name="offersprovided", name="provider",),
        migrations.RemoveField(model_name="provider", name="offers",),
        migrations.AddField(
            model_name="provider",
            name="coveredCitiesGoods",
            field=models.ManyToManyField(
                related_name="covered_cities_goods",
                to="cities_light.city",
                verbose_name="covered cities for goods",
            ),
        ),
        migrations.AddField(
            model_name="provider",
            name="coveredCitiesServices",
            field=models.ManyToManyField(
                related_name="covered_cities_services",
                to="cities_light.city",
                verbose_name="covered cities for services",
            ),
        ),
        migrations.AddField(
            model_name="provider",
            name="coveredCitiesWorks",
            field=models.ManyToManyField(
                related_name="covered_cities_works",
                to="cities_light.city",
                verbose_name="covered cities for works",
            ),
        ),
        migrations.DeleteModel(name="Offer",),
        migrations.DeleteModel(name="OffersProvided",),
        migrations.AddField(
            model_name="workexecuted",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contractor",
                to="providers.provider",
            ),
        ),
        migrations.AddField(
            model_name="servicesprovided",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_provider",
                to="providers.provider",
            ),
        ),
        migrations.AddField(
            model_name="servicesprovided",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="providers.service"
            ),
        ),
        migrations.AddField(
            model_name="goodsprovided",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goods_provider",
                to="providers.provider",
            ),
        ),
        migrations.AddField(
            model_name="provider",
            name="goods",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                through="providers.GoodsProvided",
                to="providers.good",
                verbose_name="good provided",
            ),
        ),
        migrations.AddField(
            model_name="provider",
            name="services",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                through="providers.ServicesProvided",
                to="providers.service",
                verbose_name="services provided",
            ),
        ),
        migrations.AddField(
            model_name="provider",
            name="works",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                through="providers.WorkExecuted",
                to="providers.work",
                verbose_name="works executed",
            ),
        ),
    ]
