# Generated by Django 4.2.8 on 2023-12-18 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0004_alter_provider_goods_remove_provider_goods_orgin_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="good", name="category",),
    ]
