# Generated by Django 4.2.8 on 2023-12-19 09:06

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        (
            "providers",
            "0006_rename_coveredcitiesgoods_provider_covered_cities_goods_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="provider",
            name="advantages",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("after sales service", "after sales service"),
                    ("discounts/rebates", "Discounts/rebates"),
                    ("on-site deliveries", "On-site deliveries"),
                ],
                max_length=2048,
                null=True,
                verbose_name="proposed advantages",
            ),
        ),
    ]
