# Generated by Django 4.2.8 on 2023-12-19 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0007_alter_provider_advantages"),
    ]

    operations = [
        migrations.RenameField(
            model_name="goodsprovided", old_name="good", new_name="goods",
        ),
        migrations.RenameField(
            model_name="workexecuted", old_name="good", new_name="works",
        ),
        migrations.AlterUniqueTogether(
            name="goodsprovided", unique_together={("provider", "goods")},
        ),
        migrations.AlterUniqueTogether(
            name="servicesprovided", unique_together={("provider", "service")},
        ),
        migrations.AlterUniqueTogether(
            name="workexecuted", unique_together={("provider", "works")},
        ),
        migrations.RemoveField(model_name="goodsprovided", name="created_at",),
        migrations.RemoveField(model_name="servicesprovided", name="created_at",),
        migrations.RemoveField(model_name="workexecuted", name="created_at",),
    ]
