# Generated by Django 4.2.8 on 2023-12-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0008_rename_good_goodsprovided_goods_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="provider",
            name="rccm",
            field=models.CharField(max_length=15, null=True, verbose_name="R.C.C.M"),
        ),
        migrations.AlterField(
            model_name="provider",
            name="tax_id",
            field=models.CharField(max_length=15, null=True, verbose_name="tax id"),
        ),
    ]
