# Generated by Django 4.2.8 on 2023-12-21 15:12

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0009_alter_provider_rccm_alter_provider_tax_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="provider",
            name="advantages",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("after sales service", "After sales service"),
                    ("discounts/rebates", "Discounts/rebates"),
                    ("on-site deliveries", "On-site deliveries"),
                ],
                max_length=2048,
                null=True,
                verbose_name="proposed advantages",
            ),
        ),
        migrations.AlterField(
            model_name="provider",
            name="goods",
            field=models.ManyToManyField(
                blank=True,
                through="providers.GoodsProvided",
                to="providers.good",
                verbose_name="good provided",
            ),
        ),
        migrations.AlterField(
            model_name="provider",
            name="selection_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("tender", "On tender call"),
                    ("consultation", "Restricted consultation"),
                    ("excusive", "On direct order"),
                ],
                default="tender",
                max_length=50,
                null=True,
                verbose_name="mode of selection",
            ),
        ),
        migrations.AlterField(
            model_name="provider",
            name="services",
            field=models.ManyToManyField(
                blank=True,
                through="providers.ServicesProvided",
                to="providers.service",
                verbose_name="services provided",
            ),
        ),
        migrations.AlterField(
            model_name="provider",
            name="works",
            field=models.ManyToManyField(
                blank=True,
                through="providers.WorkExecuted",
                to="providers.work",
                verbose_name="works executed",
            ),
        ),
    ]
