# Generated by Django 4.2.8 on 2023-12-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cities_light", "0011_alter_city_country_alter_city_region_and_more"),
        ("providers", "0010_alter_provider_advantages_alter_provider_goods_and_more"),
    ]

    operations = [
        migrations.AlterModelTableComment(name="workexecuted", table_comment=None,),
        migrations.AlterField(
            model_name="provider",
            name="covered_cities_Goods",
            field=models.ManyToManyField(
                blank=True,
                related_name="covered_cities_goods",
                to="cities_light.city",
                verbose_name="covered cities for goods",
            ),
        ),
        migrations.AlterField(
            model_name="provider",
            name="covered_cities_services",
            field=models.ManyToManyField(
                blank=True,
                related_name="covered_cities_services",
                to="cities_light.city",
                verbose_name="covered cities for services",
            ),
        ),
        migrations.AlterField(
            model_name="provider",
            name="covered_cities_works",
            field=models.ManyToManyField(
                blank=True,
                related_name="covered_cities_works",
                to="cities_light.city",
                verbose_name="covered cities for works",
            ),
        ),
        migrations.AlterField(
            model_name="provider",
            name="national_id",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="national ID"
            ),
        ),
        migrations.AlterField(
            model_name="provider",
            name="rccm",
            field=models.CharField(max_length=50, null=True, verbose_name="R.C.C.M"),
        ),
        migrations.AlterField(
            model_name="provider",
            name="tax_id",
            field=models.CharField(max_length=50, null=True, verbose_name="tax id"),
        ),
    ]
