# Generated by Django 4.2.8 on 2024-02-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0017_evaluation_site_site_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='address',
            field=models.TextField(max_length=500, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='affiliations',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='affiliations'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='competition',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='competition'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='contacts',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='contacts'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='equipments',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='equipments'),
        ),
    ]
