# Generated by Django 4.2.8 on 2024-03-07 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0024_alter_provider_offers_previously_provided'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='affiliations',
            field=models.TextField(blank=True, help_text='Is the provider part of a syndicate or an assciation.', max_length=500, null=True, verbose_name='affiliations'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='equipments',
            field=models.TextField(blank=True, max_length=2500, null=True, verbose_name='equipments'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='goods_orgin',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='origin of goods'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='subsidiaries',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='subsidiaries/representations'),
        ),
    ]
