# Generated by Django 4.2.8 on 2024-03-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0025_alter_provider_affiliations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='workspaces',
            field=models.CharField(blank=True, help_text='Area of your workshops/offices/stores in square meters.', max_length=500, null=True, verbose_name='workspace'),
        ),
    ]
